Validate required variables
DOCKER_HUB_REPOSITORY is a part of Docker image name, and it should be provided in the repository variables

diff --git a/.github/workflows/build-gradle-project.yaml b/.github/workflows/build-gradle-project.yaml
--- a/.github/workflows/build-gradle-project.yaml
+++ b/.github/workflows/build-gradle-project.yaml
@@ -42,6 +42,12 @@ jobs:
       NAMESPACE: ${{ vars.DOCKER_HUB_USERNAME }}
       IMAGE_NAME: ${{ vars.DOCKER_HUB_REPOSITORY }}
     steps:
+      - name: Validate required variables
+        run: |
+          if [ -z "${{ vars.DOCKER_HUB_REPOSITORY }}" ]; then
+            echo "Error: DOCKER_HUB_REPOSITORY is not set."
+            exit 1
+          fi
       - name: Download artifact
         uses: actions/download-artifact@v4
         with:
